site_name: virtual_dataframe
site_url: https://github.com/pprados/virtual_dataframe
repo_url: https://github.com/pprados/virtual_dataframe
theme: readthedocs
nav:
    - Home: README.md
    - Contribute: 'contribute.md'
    - Commands: 'commands.md'
    - Changelog: 'CHANGELOG.md'

