# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#

# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#channels
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - nvidia
    - rapidsai
    - conda-forge
  # targets is a list of 2-lists, where the first element is the
  # channel to push to and the second element is the label on that channel
  targets:
    - ["conda-forge", "main"]

build_platform:
  linux_64: linux_64
  linux_64_cuda_102: linux_64_cuda_102
# FIXME
#  linux_64_cuda_110: linux_64_cuda_110
#  linux_64_cuda_111: linux_64_cuda_111
#  linux_64_cuda_112: linux_64_cuda_112
#  linux_ppc64le: linux_ppc64le
#  linux_aarch64: linux_aarch64
#  osx_64: osx_64
#  osx_arm64: osx_arm64
#  win_64: win_64

build_with_mambabuild:
  True

noarch_platforms: linux_64