{% set NAME = environ['PRJ'] %}
{% set PRJ_VERSION = environ['GIT_DESCRIBE_TAG'] %}
{% set PRJ_URL = environ["PRJ_URL"] %}
{% set PRJ_DOC_URL = environ["PRJ_DOC_URL"] %}
{% set PRJ_PACKAGE = environ["PRJ_PACKAGE"] %}
{% set PYTHON_VERSION = environ["PYTHON_VERSION"] %}
{% set PYTHON_VERSION_MAX = environ["PYTHON_VERSION_MAX"] %}
{% set WHEEL = environ["WHEEL"] %}

package:
  {% if vdf_mode %}
  name: "{{ NAME|lower }}-{{ vdf_mode }}"
  {% else %}
  name: "{{ NAME|lower }}"
  {% endif %}
  version: "{{ PRJ_VERSION }}"

source:
  path: .
#  git_url: {{ REMOTE_GIT_URL }}
#  git_rev: {{ PRJ_VERSION }}
#  git_depth: 1

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: "python -m pip install {{ WHEEL }} --no-deps --ignore-installed -vv"

requirements:
  build:
    - python {{ PYTHON_VERSION }}
    - pip
    - setuptools
    - setuptools_scm

  run:
    {% if vdf_mode in ('all', 'cudf', 'dask_cudf') %}
    - python>={{ PYTHON_VERSION }},<={{ PYTHON_VERSION_MAX }}
    {% else %}
    - python>={{ PYTHON_VERSION }}
    {% endif %}
    - python-dotenv
    - numba>=0.55
    - pandas>=1.3
    {% if vdf_mode != '' %}
    - numpy>=1.21
    {% if vdf_mode in ('all', 'modin', 'dask_modin') %}
    - modin-core>=0.15
    {% endif %}
    {% if vdf_mode in ('all', 'cudf', 'dask_cudf') %}
    - cudf>=22.08
    - cudatoolkit>=11.6
    {% endif %}
    {% if vdf_mode in ('all', 'dask', 'dask_cudf', 'dask_modin') %}
#    - dask
    - dask-core>=2022.2
    - distributed>=2022.2
    - bokeh>=2.1.1
    - cytoolz>=0.8.2
    - jinja2
    {% endif %}
    {% if vdf_mode in ('all', 'dask_cudf') %}
    - dask-cudf>=22.4
    - dask-cuda>=22.4
    {% endif %}
#    {% if vdf_mode in ('all', 'ray_modin') %}
#    - ray>=0.15.2
#    {% endif %}
    {% endif %} # vdf_mode != ''

test:
  commands:
    - echo "PREFIX=${PREFIX} VDF_MODE={{ vdf_mode }} PPR"
    {% if vdf_mode != "" %}
    {% if vdf_mode != "all" %}
    - VDF_MODE="{{ vdf_mode }}" python -c 'from {{ PRJ_PACKAGE }} import *'
    {% else %}
    - VDF_MODE="pandas"     python -c 'from {{ PRJ_PACKAGE }} import *'
    - VDF_MODE="cudf"       python -c 'from {{ PRJ_PACKAGE }} import *'
    - VDF_MODE="modin"      python -c 'from {{ PRJ_PACKAGE }} import *'
    - VDF_MODE="dask"       python -c 'from {{ PRJ_PACKAGE }} import *'
    - VDF_MODE="dask_cudf"  python -c 'from {{ PRJ_PACKAGE }} import *'
    - VDF_MODE="dask_modin" python -c 'from {{ PRJ_PACKAGE }} import *'
#    - VDF_MODE=ray_modin  python -c 'from {{ PRJ_PACKAGE }} import *'
    {% endif %} # Default, all
    {% endif %} # core

about:
  home:    {{ PRJ_URL }}
  doc_url: {{ PRJ_DOC_URL }}
  license: Apache v2
  summary: Bridge between pandas, cudf, modin, dask and dask-cudf

extra:
  copy_test_spirce_files: false
  copy_test_source_files: false
  recipe-maintainers:
    - github@prados.fr
